services:
  flask_app:
    build: .
    # image: api_logix_flask_app
    container_name: flask_app
    # tty: true
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./flask_app:/app
    #   - ./flask_app/sqlhosts:/opt/IBM/Informix_Client-SDK/etc/sqlhosts
    #   - ./files:/app/static/files
    # env_file:
    #   - .env
    # ports:
    #   - "8000:8000"
    # command: gunicorn --reload -w 1 -b 0.0.0.0:8000 wsgi:server
    command: gunicorn --reload -w 1 -b 0.0.0.0:8000 wsgi:app
  nginx:
    image: nginx:latest
  #   tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certificado:/etc/nginx/certificado
  #     - ./files:/files
    depends_on:
      - flask_app