 services:

  traefik:
    image: traefik:latest
    command:
    - "--api.dashboard=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
    - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
    - "--certificatesresolvers.letsencryptresolver.acme.email=opabloedu@gmail.com"
    - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    - "--log.level=DEBUG"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./traefik/letsencrypt:/letsencrypt
    restart: always

  flask_app:
    build: ./flask_app
    container_name: app_flask
    restart: always
    env_file:
      - .env 
    volumes:
      - ./flask_app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask-app.rule=Host(`backend.caiuas.com.br`)"
      - "traefik.http.routers.flask-app.entrypoints=websecure"
      - "traefik.http.routers.flask-app.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.flask-app.loadbalancer.server.port=5000" # Porta padrão do Flask
    command: "flask run --host=0.0.0.0 --port=5000"
  
  streamlit_app:
    build: ./streamlit_app
    container_name: app_streamlit
    restart: always
    # manter ligado
    tty: true
    env_file:
      - .env 
    volumes:
      - ./streamlit_app:/app
    # libera rede para fora
    ports:
      - "8501:8501" # Porta padrão do Streamlit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamlit-app.rule=Host(`bi.caiuas.com.br`)"
      - "traefik.http.routers.streamlit-app.entrypoints=web,websecure"
      - "traefik.http.routers.streamlit-app.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.streamlit-app.loadbalancer.server.port=8501" # Porta padrão do Streamlit
    command: "streamlit run app.py --server.port 8501 --server.address 0.0.0.0"

  worker_integracao_des:
    build: ./workers/estoque_veiculos_des
    container_name: worker_integracao_des
    restart: always
    tty: True
    env_file:
      - .env 
    volumes:
      - ./workers/estoque_veiculos_des:/app
    command: "bash -c 'python3 estoque_veiculos.py & python3 agendamentos.py & wait'"
  
  worker_update_questionario:
    build: ./workers/update_questionario
    container_name: worker_update_questionario
    restart: always
    # tty: true
    env_file:
      - .env 
    volumes:
      - ./workers/update_questionario:/app
    command: "python3 app.py"

  worker_pesquisa:
    build: ./workers/pesquisa
    container_name: worker_pesquisa
    restart: always
    tty: true
    env_file:
      - .env 
    volumes:
      - ./workers/pesquisa:/app
    # command: "python3 app.py"
    
  worker_cria_pesquisa:
    build: ./workers/cria_pesquisa
    container_name: worker_cria_pesquisa
    restart: always
    tty: true
    env_file:
      - .env 
    volumes:
      - ./workers/cria_pesquisa:/app
    command: "python3 app.py"

  worker_update_fechamento_crm:
    build: ./workers/update_fechamento_crm
    container_name: worker_update_fechamento_crm
    restart: always
    tty: true
    env_file:
      - .env 
    volumes:
      - ./workers/update_fechamento_crm:/app
    command: "python3 app.py"

  # worker_myhonda:
  #   build: ./workers/myhonda
  #   # mem_limit: 2g
  #   container_name: worker_myhonda
  #   restart: always
  #   tty: true
  #   env_file:
  #     - .env 
  #   volumes:
  #     - ./workers/myhonda:/app
  #   command: "python3 app.py"

  worker_envia_pesquisa_whatsapp:
    build: ./workers/envia_pesquisa_whatsapp
    # mem_limit: 2g
    container_name: worker_envia_pesquisa_whatsapp
    restart: always
    tty: true
    env_file:
      - .env 
    volumes:
      - ./workers/envia_pesquisa_whatsapp:/app
    command: "python3 app.py"

  worker_update_campanhas:
    image: backend-flask_app
    # mem_limit: 2g
    container_name: worker_update_campanhas
    restart: always
    # tty: true
    env_file:
      - .env 
    volumes:
      - ./workers/update_campanhas:/app
    command: "python3 app.py"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  worker_celery:
    build: ./workers/celery
    container_name: worker_celery
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - ./workers/celery:/app
      - ./flask_app:/flask_app
    command: "celery -A app worker --loglevel=info --concurrency=4 -B"

  flower:
    build: ./workers/celery
    container_name: flower
    restart: always
    env_file:
      - .env
    volumes:
      - ./workers/celery:/app
      - ./flask_app:/flask_app
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - worker_celery
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower-app.rule=Host(`flower.caiuas.com.br`)"
      - "traefik.http.routers.flower-app.entrypoints=websecure"
      - "traefik.http.routers.flower-app.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.flower-app.loadbalancer.server.port=5555"
    command: sh -c "celery -A app flower --port=5555 $${FLOWER_USER:+--basic_auth=$${FLOWER_USER}:$${FLOWER_PASSWORD}}"