server {
    listen 80;
    # server_name "endereco do site";
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    # server_name "endereco do site";

    ssl_certificate /etc/nginx/certificado/cert.pem;
    ssl_certificate_key /etc/nginx/certificado/key.pem;

    location / {
        proxy_pass http://flask_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}