server {
    listen 80;
    # Você pode adicionar outros nomes pelos quais acessa, como localhost ou intranet.caiuas.com
    server_name 192.168.16.164;

    # REMOVA a linha de redirecionamento:
    # return 301 https://$server_name$request_uri;

    location / {
        proxy_pass http://flask_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # $scheme será 'http'
    }
}